# https://github.com/helm/charts/tree/master/stable/oauth2-proxy

config:
  existingSecret: oauth2-proxy-creds

extraArgs:
  whitelist-domain: .int.mydomain.com
  cookie-domain: .int.mydomain.com
  provider: github

authenticatedEmailsFile:
  enabled: true
  restricted_access: |-
    vladislav.bondarchuk@kofax.com
    vladiksun85@gmail.com