apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openampvc
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""
