apiVersion: v1
kind: PersistentVolume
metadata:
  name: openam-local-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
#    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /DockerMounts/openam
