apiVersion: v1
kind: PersistentVolume
metadata:
  name: openam-local-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  #    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /DockerMounts/openam

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openampvc
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    #    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: ""

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: openam-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openam-app
  template:
    metadata:
      labels:
        app: openam-app
    spec:
      containers:
        - image: openidentityplatform/openam
          name: openam
          volumeMounts:
            - name: openam-volume
              mountPath: /usr/openam/config
          ports:
            - containerPort: 8080
      volumes:
        - name: openam-volume
          persistentVolumeClaim:
            claimName: openampvc

---
kind: Service
apiVersion: v1
metadata:
  name: openam-service
spec:
  selector:
    app: openam-app
  ports:
    - port: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: openam.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: openam-service
              servicePort: 8080
---

