# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
#  - role: control-plane
#  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 8090
        hostPort: 8090
  - role: worker
    extraPortMappings:
      - containerPort: 8091
        hostPort: 8091
  - role: worker
    extraPortMappings:
      - containerPort: 8093
        hostPort: 8093
#        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
#        protocol: udp # Optional, defaults to tcp