# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
#  - role: control-plane
#  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
      - containerPort: 8090
        hostPort: 8090
  - role: worker
    extraPortMappings:
      - containerPort: 30002
        hostPort: 30002
  - role: worker
    extraPortMappings:
      - containerPort: 30003
        hostPort: 30003
#        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
#        protocol: udp # Optional, defaults to tcp