apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weave
  namespace: weave
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - localhost
      secretName: tls-secret
  rules:
    - host: weave.scope.app
      http:
        paths:
          - path: /
            backend:
              serviceName: weave-scope-app
              servicePort: 4040
---
