version: "3.5"

networks:
  network:

services:
  server-0:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb1
    image: couchdb:2.3.1
    networks:
      network:
        aliases:
          - couchdb1
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - 'C:\Users\vladislav.bondarchuk\Downloads\DockerMounts\CouchDBCluster\couchdb0:/opt/couchdb/data'
  server-1:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb2
    image: couchdb:2.3.1
    networks:
      network:
        aliases:
          - couchdb2
    ports:
      - "15984:5984"
      - "15986:5986"
    volumes:
      - 'C:\Users\vladislav.bondarchuk\Downloads\DockerMounts\CouchDBCluster\couchdb1:/opt/couchdb/data'
  server-2:
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: couchdb
      NODENAME: couchdb3
    image: couchdb:2.3.1
    networks:
      network:
        aliases:
          - couchdb3
    ports:
      - "25984:5984"
      - "25986:5986"
    volumes:
      - 'C:\Users\vladislav.bondarchuk\Downloads\DockerMounts\CouchDBCluster\couchdb2:/opt/couchdb/data'

volumes:
  volume-0:
  volume-1:
  volume-2:
