# DESCRIPTION:	  Simple get started
# AUTHOR:		  Vladislav Bondarchuk
# COMMENTS:
#
#   Create docker image from Dockerfile
#   docker build -t docker-java .
#
# USAGE:
#
#
#


# Base docker image
FROM ubuntu

CMD echo "Hello world"
