# DESCRIPTION:	  Simple get started
# AUTHOR:		  Vladislav Bondarchuk
# COMMENTS:
#
#
# USAGE:
#
#
#


# Base docker image
FROM java

COPY target/hello.jar /usr/src/hello.jar

CMD java -cp /usr/src/hello.jar or .example.App
